import {authenticate,enforceOrigin} from './auth.js';
import {AppError,type Env,type Principal,type AnswerDraft,type Hit,type ConversationTurn,type PublicAnswer} from './types.js';
import {boundedText,containsObviousCredential,exactKeys,id,isId,json,object,publicHeaders,sha256} from './util.js';
import {retrieveEvidence,researchFingerprint} from './retrieval.js';
import {evidenceBudgetAnswer,extractiveAnswer,implementationProbeAnswer,jsonArtifact,markdownArtifact,projectAnswer,boundAnswer} from './answer.js';
import {checkInferenceConfiguration,infer} from './inference.js';
import {evidenceRelease,reading} from './integration.js';
interface Dependencies {
  authenticate?: (request:Request,env:Env)=>Promise<Principal>;
  infer?: (env:Env,prompt:string,hits:Hit[],signal:AbortSignal,fetcher?:never,history?:ConversationTurn[],markDispatched?:()=>Promise<void>)=>Promise<{draft:AnswerDraft;usage:unknown}>;
  allowFixtures?:boolean;
}
interface StoredRun {interaction_id:string;prompt_sha256:string;status:string;public_answer_json:string|null;started_ms:number;expires_ms:number;dispatch_state:string;retryable:number;release_id:string;conversation_id:string|null;}
async function invite(env:Env,p:Principal):Promise<void>{await env.DB.prepare('UPDATE testers SET principal_id=? WHERE email=? AND principal_id IS NULL AND enabled=1').bind(p.id,p.email).run();const t=await env.DB.prepare('SELECT enabled,principal_id FROM testers WHERE email=?').bind(p.email).first<{enabled:number;principal_id:string}>();if(!t?.enabled||t.principal_id!==p.id)throw new AppError('FORBIDDEN',403);}
function errorResponse(e:unknown):Response {const code=e instanceof AppError?e.code:'INTERNAL';const status=e instanceof AppError?e.httpStatus:503;const message=status===401?'Sign-in required.':status===403?'Access is not available.':status===404?'Not found.':status===409?'This request is already recorded or awaiting reconciliation.':status===429?'Librarian is at its current request limit.':status===400||status===413||status===415?'Please check the submitted request.':'Librarian could not complete this request. No automatic retry was started.';return json({error:status>=500?'UNAVAILABLE':code==='NOT_FOUND'?'NOT_FOUND':'REQUEST_NOT_ACCEPTED',message},status);}
function isImplementationProbe(prompt:string):boolean{return /\b(?:what|which|show|reveal|tell|identify|describe)\b[\s\S]{0,80}\b(?:model|provider|backend|system prompt|internal prompt|oauth|access token|refresh token|credential|cloudflare|hosting|architecture)\b|\b(?:system prompt|internal prompt|refresh token|access token|oauth client|cloudflare access)\b/i.test(prompt);}
async function conversationState(env:Env,p:Principal,conversationId:string|undefined,release:string,now:number):Promise<{history:ConversationTurn[];nextOrdinal:number}|null>{
  if(conversationId===undefined)return null;if(!isId(conversationId))throw new AppError('INVALID_INPUT');
  const c=await env.DB.prepare('SELECT principal_id,release_id FROM conversations WHERE conversation_id=?').bind(conversationId).first<{principal_id:string;release_id:string}>();
  if(!c){await env.DB.prepare('INSERT INTO conversations(conversation_id,principal_id,release_id,created_ms,updated_ms) VALUES(?,?,?,?,?)').bind(conversationId,p.id,release,now,now).run();return {history:[],nextOrdinal:1};}
  if(c.principal_id!==p.id)throw new AppError('NOT_FOUND',404);if(c.release_id!==release)throw new AppError('CONVERSATION_SNAPSHOT_MISMATCH',409);
  const rows=await env.DB.prepare('SELECT ordinal,role,content FROM conversation_turns WHERE conversation_id=? ORDER BY ordinal DESC LIMIT 12').bind(conversationId).all<{ordinal:number;role:'user'|'assistant';content:string}>();
  const ordered=[...rows.results].reverse(),history:ConversationTurn[]=[];let bytes=0;for(const r of ordered){const n=new TextEncoder().encode(r.content).byteLength;if(bytes+n>20000)continue;history.push({role:r.role,content:r.content});bytes+=n;}
  const next=rows.results.length?Math.max(...rows.results.map(r=>r.ordinal))+1:1;return {history,nextOrdinal:next};
}
function historyAnswer(a:PublicAnswer):string {
 if(a.evidence_release?.profile==='publication-v1.2-strict'){
  // E identifiers are local to one answer. Do not feed context-stripped mechanics prose
  // back as assistant truth in a later request; the full answer remains in runs/downloads.
  const reference={kind:'previous_answer_reference_only',notice:'Earlier answer is not evidence for this request. Retrieve the current complete evidence packet; local E identifiers do not carry over.',release:a.evidence_release,evidence:a.citations.map(c=>({card_id:c.card_id,class:c.class,snapshot:c.snapshot}))};
  let text=JSON.stringify(reference);if(new TextEncoder().encode(text).byteLength>10000)text=JSON.stringify({kind:reference.kind,notice:reference.notice,release_id:a.evidence_release.release_id});return text;
 }
 let text=a.paragraphs.map(p=>p.text).join('\n\n');if(new TextEncoder().encode(text).byteLength>10000)text=text.slice(0,9000)+'\n\n[Earlier response compacted in conversation history; evidence is re-retrieved for each new question.]';return text;
}
const AMBIGUOUS=new Set(['PROVIDER_UNCERTAIN','PROVIDER_PROTOCOL','PROVIDER_TRUNCATED','PROVIDER_TOO_LARGE']);
const RETRYABLE_KNOWN=new Set(['PROVIDER_LIMIT','PROVIDER_REJECTED','RETRIEVAL_UNAVAILABLE','INFERENCE_UNAVAILABLE']);
export function createApp(deps:Dependencies={}) {
 const authenticateRequest=deps.authenticate??authenticate, generate=deps.infer??infer;
 return {async fetch(request:Request,env:Env):Promise<Response>{
  try{
    enforceOrigin(request,env.PUBLIC_ORIGIN);const p=await authenticateRequest(request,env);await invite(env,p);const u=new URL(request.url);
    if(request.method==='GET'&&u.pathname==='/api/health')return json({ready:true});
    if(request.method==='GET'&&u.pathname==='/api/library'){
      const release=await activeRelease(env,!!deps.allowFixtures);const adapter=await env.DB.prepare('SELECT contract FROM release_adapters WHERE release_id=?').bind(release).first<{contract:string}>();
      if([...u.searchParams.keys()].some(k=>k!=='card_id')||u.searchParams.getAll('card_id').length>1)throw new AppError('INVALID_INPUT');
      if(adapter){const cardId=u.searchParams.get('card_id');if(cardId)return json(await reading(env.DB,cardId,release,!!deps.allowFixtures));
        const items=await env.DB.prepare(`SELECT record_json FROM publication_cards WHERE release_id=? AND is_superseded=0 AND (publication='tester_approved' OR ?=1) ORDER BY card_id LIMIT 30`).bind(release,deps.allowFixtures?1:0).all<{record_json:string}>();
        return json({navigation_only:true,notice:'First 30 entries. Open an entry for its complete evidence and required context.',evidence_release:await evidenceRelease(env.DB,release,!!deps.allowFixtures),items:items.results.map(r=>{const c=JSON.parse(r.record_json);return {card_id:c.card_id,title:c.title,text:'Open this entry for the complete evidence and required context.',status:c.class,assumptions:[]};})});
      }
      const items=await env.DB.prepare(`SELECT record_json FROM chunks WHERE release_id=? AND (publication='tester_approved' OR ?=1) ORDER BY chunk_id LIMIT 30`).bind(release,deps.allowFixtures?1:0).all<{record_json:string}>();return json({items:items.results.map(r=>{const c=JSON.parse(r.record_json);return {title:c.heading,text:c.body,status:c.fidelity,assumptions:[...c.assumptions,...c.unresolved]};})});
    }
    if(request.method==='POST'&&u.pathname==='/api/ask'){
      const raw=object(JSON.parse(await boundedText(request.body,16384)));exactKeys(raw,['prompt','request_id','conversation_id']);
      if(typeof raw.prompt!=='string'||raw.prompt.trim().length<2||raw.prompt.length>4000||!isId(raw.request_id)||(raw.conversation_id!==undefined&&!isId(raw.conversation_id)))throw new AppError('INVALID_INPUT');
      const prompt=raw.prompt.trim(),requestKey=raw.request_id,conversationId=raw.conversation_id as string|undefined;if(containsObviousCredential(prompt))throw new AppError('SENSITIVE_INPUT');const digest=await sha256(prompt),now=Date.now();
      const previous=await env.DB.prepare('SELECT interaction_id,prompt_sha256,status,public_answer_json,started_ms,expires_ms,dispatch_state,retryable,release_id,conversation_id FROM runs WHERE principal_id=? AND request_key=?').bind(p.id,requestKey).first<StoredRun>();
      if(previous){if(previous.prompt_sha256!==digest||(previous.conversation_id??undefined)!==conversationId)throw new AppError('CONFLICT',409);if(previous.status==='completed'&&previous.public_answer_json)return json(JSON.parse(previous.public_answer_json));if(previous.status==='unknown')throw new AppError('REQUEST_OUTCOME_UNKNOWN',409);if(previous.status==='running'&&previous.expires_ms>now)throw new AppError('PENDING',409);if(previous.status==='running'&&previous.dispatch_state!=='pre_dispatch'){await env.DB.prepare(`UPDATE runs SET status='unknown',completed_ms=?,error_code='REQUEST_OUTCOME_UNKNOWN',retryable=0 WHERE interaction_id=? AND status='running'`).bind(now,previous.interaction_id).run();throw new AppError('REQUEST_OUTCOME_UNKNOWN',409);}if(previous.status==='failed'&&!previous.retryable)throw new AppError('PENDING',409);}
      const implementationProbe=isImplementationProbe(prompt),release=await activeRelease(env,!!deps.allowFixtures);if(previous&&previous.release_id!==release)throw new AppError('CONFLICT',409);if(!implementationProbe)checkInferenceConfiguration(env);
      const conv=await conversationState(env,p,conversationId,release,now);const runId=previous?.interaction_id??id();
      if(previous){const reclaimed=await env.DB.prepare(`UPDATE runs SET status='running',started_ms=?,expires_ms=?,completed_ms=NULL,error_code=NULL,diagnostic_json=NULL,dispatch_state='pre_dispatch',retryable=0,retrieved_chunk_ids='[]' WHERE interaction_id=? AND status=? AND started_ms=? AND expires_ms=? AND ((status='failed' AND retryable=1) OR (status='running' AND dispatch_state='pre_dispatch' AND expires_ms<=?))`).bind(now,now+120000,runId,previous.status,previous.started_ms,previous.expires_ms,now).run();if(reclaimed.meta.changes!==1)throw new AppError('CONFLICT',409);}
      else {try{await env.DB.prepare(`INSERT INTO runs(interaction_id,principal_id,tester_email,request_key,prompt_sha256,prompt,release_id,mode,status,started_ms,expires_ms,conversation_id,dispatch_state,retryable) VALUES(?,?,?,?,?,?,?,?,'running',?,?,?,'pre_dispatch',0)`).bind(runId,p.id,p.email,requestKey,digest,prompt,release,env.INFERENCE_MODE,now,now+120000,conversationId??null).run();}catch{throw new AppError('BUSY_OR_LIMIT',429);}}
      let dispatched=false;
      try{
        let hits:Hit[]=[],draft:AnswerDraft,usage:unknown=null,researchRecorded=false;
        if(implementationProbe)draft=implementationProbeAnswer();
        else {const context=await evidenceRelease(env.DB,release,!!deps.allowFixtures);const selected=await retrieveEvidence(env.DB,prompt,release,context.profile==='publication-v1.2-strict'?6:5,!!deps.allowFixtures);hits=selected.hits;await env.DB.prepare('UPDATE runs SET retrieved_chunk_ids=? WHERE interaction_id=?').bind(JSON.stringify(hits.map(h=>h.chunk.chunk_id)),runId).run();if(selected.status==='EVIDENCE_BUDGET_EXCEEDED')draft=evidenceBudgetAnswer();else if(env.INFERENCE_MODE==='extractive'||selected.status==='NO_SUPPORTED_EVIDENCE')draft=extractiveAnswer(hits);else {const mark=async()=>{const r=await env.DB.prepare(`UPDATE runs SET dispatch_state='dispatched' WHERE interaction_id=? AND status='running' AND dispatch_state='pre_dispatch'`).bind(runId).run();if(r.meta.changes!==1)throw new AppError('DISPATCH_STATE',503);dispatched=true;};const result=await generate(env,prompt,hits,request.signal,undefined,conv?.history??[],mark);draft=result.draft;usage=result.usage;}researchRecorded=draft.research_needed;}
        let answer=projectAnswer(draft,hits,runId,researchRecorded);answer.evidence_release=await evidenceRelease(env.DB,release,!!deps.allowFixtures);answer=boundAnswer(answer);researchRecorded=answer.research_recorded;const statements=[env.DB.prepare(`UPDATE runs SET status='completed',completed_ms=?,public_answer_json=?,usage_json=?,retryable=0 WHERE interaction_id=? AND status='running'`).bind(Date.now(),JSON.stringify(answer),JSON.stringify(usage),runId)];
        if(researchRecorded)statements.push(env.DB.prepare(`INSERT OR IGNORE INTO research_candidates(candidate_id,interaction_id,release_id,question,fingerprint,created_ms) VALUES(?,?,?,?,?,?)`).bind(id(),runId,release,prompt,await sha256(researchFingerprint(prompt)),Date.now()));
        if(conv&&conversationId){statements.push(env.DB.prepare('INSERT INTO conversation_turns(conversation_id,ordinal,role,content,interaction_id) VALUES(?,?,?,?,?)').bind(conversationId,conv.nextOrdinal,'user',prompt,runId));statements.push(env.DB.prepare('INSERT INTO conversation_turns(conversation_id,ordinal,role,content,interaction_id) VALUES(?,?,?,?,?)').bind(conversationId,conv.nextOrdinal+1,'assistant',historyAnswer(answer),runId));statements.push(env.DB.prepare('UPDATE conversations SET updated_ms=? WHERE conversation_id=?').bind(Date.now(),conversationId));}
        await env.DB.batch(statements);await invite(env,p);return json(answer);
      }catch(e){const code=e instanceof AppError?e.code:'INTERNAL';const uncertain=code==='PROVIDER_UNCERTAIN'||(dispatched&&(!(e instanceof AppError)||AMBIGUOUS.has(code)));const retryable=!uncertain&&RETRYABLE_KNOWN.has(code);await env.DB.prepare(`UPDATE runs SET status=?,completed_ms=?,error_code=?,diagnostic_json=?,retryable=? WHERE interaction_id=? AND status='running'`).bind(uncertain?'unknown':'failed',Date.now(),code,JSON.stringify(e instanceof AppError?e.diagnostic??null:null),retryable?1:0,runId).run().catch(()=>{});throw e;}
    }
    const artifact=/^\/api\/answers\/([0-9a-f-]+)\/file$/.exec(u.pathname);if(request.method==='GET'&&artifact){if(!isId(artifact[1]))throw new AppError('NOT_FOUND',404);const format=u.searchParams.get('format');if(!['md','json'].includes(format??'')||[...u.searchParams.keys()].some(k=>k!=='format'))throw new AppError('INVALID_INPUT');const row=await env.DB.prepare(`SELECT public_answer_json,prompt FROM runs WHERE interaction_id=? AND principal_id=? AND status='completed'`).bind(artifact[1],p.id).first<{public_answer_json:string;prompt:string}>();if(!row)throw new AppError('NOT_FOUND',404);const answer=JSON.parse(row.public_answer_json) as PublicAnswer;const body=format==='md'?markdownArtifact(answer,row.prompt):jsonArtifact(answer,row.prompt);return new Response(body,{headers:publicHeaders({'Content-Type':format==='md'?'text/plain; charset=utf-8':'application/json; charset=utf-8','Content-Disposition':'attachment; filename="librarian-answer.'+format+'"'})});}
    if(request.method==='POST'&&u.pathname==='/api/feedback'){const v=object(JSON.parse(await boundedText(request.body,8192)));exactKeys(v,['interaction_id','rating','note']);if(!isId(v.interaction_id)||!['useful','wrong','missing_evidence','needs_research'].includes(String(v.rating))||(v.note!==undefined&&(typeof v.note!=='string'||v.note.length>1000||containsObviousCredential(v.note))))throw new AppError('INVALID_INPUT');const owned=await env.DB.prepare('SELECT interaction_id FROM runs WHERE interaction_id=? AND principal_id=? AND status=\'completed\'').bind(v.interaction_id,p.id).first();if(!owned)throw new AppError('NOT_FOUND',404);await env.DB.prepare(`INSERT INTO feedback(interaction_id,principal_id,rating,note,created_ms) VALUES(?,?,?,?,?) ON CONFLICT(interaction_id,principal_id) DO UPDATE SET rating=excluded.rating,note=excluded.note,created_ms=excluded.created_ms`).bind(v.interaction_id,p.id,v.rating,v.note??'',Date.now()).run();return json({recorded:true});}
    if((request.method==='GET'||request.method==='HEAD')&&['/','/index.html','/app.js','/style.css','/readings'].includes(u.pathname)){const assetUrl=new URL(request.url);if(assetUrl.pathname==='/readings')assetUrl.pathname='/index.html';const r=await env.ASSETS.fetch(new Request(assetUrl,{method:request.method}));const headers=publicHeaders({'Content-Type':r.headers.get('Content-Type')??'application/octet-stream'});return new Response(request.method==='HEAD'?null:r.body,{status:r.status,headers});}
    throw new AppError('NOT_FOUND',404);
  }catch(e){if(e instanceof SyntaxError)e=new AppError('INVALID_INPUT');return errorResponse(e);}
 }};
}
async function activeRelease(env:Env,allowFixture:boolean):Promise<string>{const r=await env.DB.prepare('SELECT r.release_id,r.status FROM releases r JOIN app_settings s ON s.active_release=r.release_id WHERE s.singleton=1').first<{release_id:string;status:string}>();if(!r||(r.status!=='published'&&!(allowFixture&&r.status==='fixture')))throw new AppError('NO_PUBLISHED_CORPUS',503);return r.release_id;}
